kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    name: jupiterone-integration
  name: jupiterone-integration-cluster
subjects:
  - kind: ServiceAccount
    name: jupiterone-integration-cluster
    namespace: default
roleRef:
  kind: ClusterRole
  name: jupiterone-integration-cluster-readonly
  apiGroup: rbac.authorization.k8s.io
