apiVersion: batch/v1
kind: CronJob
metadata:
  name: integration-deployment-cron
  labels:
    name: jupiterone-integration
    app: integration-cron
spec:
  schedule: "*/60 * * * *" # Schedule to run every hour
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: jupiterone-integration-cluster
          containers:
            - name: jupiterone-integration
              image: jupiterone/graph-kubernetes:latest
              imagePullPolicy: IfNotPresent
              env:
                # could use better name, but for now:
                # ACCESS_TYPE can either be "namespace" or "cluster"
                - name: ACCESS_TYPE
                  value: "cluster"
                # If ACCESS_TYPE === "namespace"
                # This needs to contain its name
                - name: NAMESPACE
                  value: "default"
                - name: JUPITERONE_ACCOUNT_ID
                  valueFrom:
                    secretKeyRef:
                      name: jupiterone-integration-secret
                      key: jupiteroneAccountId
                - name: JUPITERONE_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: jupiterone-integration-secret
                      key: jupiteroneApiKey
                - name: INTEGRATION_INSTANCE_ID
                  valueFrom:
                    secretKeyRef:
                      name: jupiterone-integration-secret
                      key: jupiteroneIntegrationInstanceId
                - name: IS_RUNNING_TEST
                  value: "false"
              resources:
                limits:
                  cpu: 1000m
                  memory: 1024Mi
          restartPolicy: Never
