apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: integration-deployment-cron
  labels:
    app: integration-cron
spec:
  schedule: "*/60 * * * *" # Schedule to run every 10 minutes
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: namespace-sa
          containers:
          - name: integration
            image: my-new-image
            imagePullPolicy: IfNotPresent
            env:
              # could use better name, but for now:
              # ACCESS_TYPE can either be "namespace" or "cluster"
              - name: ACCESS_TYPE
                value: 'namespace'
              # If ACCESS_TYPE === "namespace"
              # This needs to contain its name
              - name: NAMESPACE
                value: 'default'
              - name: JUPITERONE_ACCOUNT
                valueFrom:
                  secretKeyRef:
                    name: jone-secret
                    key: jaccountid
              - name: JUPITERONE_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: jone-secret
                    key: japikey
              - name: INTEGRATION_ID
                valueFrom:
                  secretKeyRef:
                    name: jone-secret
                    key: integrationid
          restartPolicy: Never
