apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-deployment
  labels:
    app: integration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration
  template:
    metadata:
      labels:
        app: integration
    spec:
      serviceAccountName: namespace-sa
      containers:
        - name: integration
          image: my-new-image
          imagePullPolicy: IfNotPresent
          env:
            # could use better name, but for now:
            # ACCESS_TYPE can either be "namespace" or "cluster"
            - name: ACCESS_TYPE
              value: 'namespace'
            # If ACCESS_TYPE === "namespace"
            # This needs to contain its name
            - name: NAMESPACE
              value: 'default'
            - name: JUPITERONE_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: jupiterone-integration-secret
                  key: jaccountid
            - name: JUPITERONE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: jupiterone-integration-secret
                  key: japikey
            - name: INTEGRATION_INSTANCE_ID
              valueFrom:
                secretKeyRef:
                  name: jupiterone-integration-secret
                  key: integrationid
