apiVersion: batch/v1
kind: Job
metadata:
  name: integration-job
spec:
  template:
    spec:
      serviceAccountName: cluster-sa
      containers:
        - name: integration
          image: my-new-image
          imagePullPolicy: IfNotPresent
          env:
            # could use better name, but for now:
            # ACCESS_TYPE can either be "namespace" or "cluster"
            - name: ACCESS_TYPE
              value: 'cluster'
            # If ACCESS_TYPE === "namespace"
            # This needs to contain its name
            - name: NAMESPACE
              value: 'default'
            - name: IS_RUNNING_TEST
              value: 'false'
            - name: JUPITERONE_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: jupiterone-integration-secret
                  key: jaccountid
            - name: JUPITERONE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: jupiterone-integration-secret
                  key: japikey
            - name: INTEGRATION_INSTANCE_ID
              valueFrom:
                secretKeyRef:
                  name: jupiterone-integration-secret
                  key: integrationid
      restartPolicy: Never
  backoffLimit: 4
